### ISSUE TITLE
Which dependicies do I have to declare to use assistedinject and multibindings?

### ISSUE THREAD

**Issue by martinbrylski** [roboguice/roboguice#281] opened 2014-12-11 09:36 UTC
I want to use roboguice using this dependency declaration in build.gradle:

```
dependencies {
    compile 'org.roboguice:roboguice:3.+'
}
```

I additionally want to use assistedinject and multibindigs. What do I need to add?

**Comment by stephanenicolas** [comment] 2015-01-13 16:46
duplicate of https://github.com/roboguice/roboguice/issues/275

**Closed by stephanenicolas** 2015-01-13 16:46 UTC
